### PR TITLE
Add support for latest cordova-ios

### PR DESCRIPTION
**Pull request by asrytis**
This PR removes unused icon & adds support for all the missing ones. My dev environment:
- cordova 7.1.0 (latest)
- cordova-ios 4.5.2 (latest)
- Mac OS X 10.12.6
- XCode 9.0.1 (latest)

See picture below for side by side comparison between stock cordova, current cordova-icon & my PR:

comparison

### CODE REVIEW

**Comment by asrytis** [comment]
Source of icon sizes:
https://github.com/apache/cordova-ios/pull/341
https://issues.apache.org/jira/browse/CB-12896

**Comment by AlexDisler** [comment]
Thank you

**Comment by asrytis** [comment]
Happy to contribute! Are you planning an npm release any time soon?

**Comment by AlexDisler** [comment]
Yeah, released to npm

**Pull request merged**
